language: ruby
rvm:
  - 2.1.7
cache: bundler
sudo: false
before_script: bundle update
script: ./script/cibuild
notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
