# Site settings
title: Artificial Intelligence Computer Science Club
email:
description: > # this means to ignore newlines until "baseurl:"
    Meetings are held the first and thrid Fridays of the month in room B11
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aicsc.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
encoding: "UTF-8"
lang: en-US
timezone: "America/Los_Angeles"
lsi: false
permalink: /:year/:month/:title.html
sass:
    style: :compressed
markdown: kramdown
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    use_coderay: false
gems:
    - jekyll-sass-converter
    - jekyll-sitemap
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "minutes"
      title: "Meeting Minutes"

exclude:
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - readme.md
